USE [master]
GO

/****** Object:  Database [LunchBox]    Script Date: 11/11/2014 13:10:04 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'LunchBox')
DROP DATABASE [LunchBox]
GO

USE [master]
GO

/****** Object:  Database [LunchBox]    Script Date: 11/11/2014 13:10:04 ******/
CREATE DATABASE [LunchBox] ON  PRIMARY 
( NAME = N'LunchBox', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\LunchBox.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LunchBox_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\LunchBox_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LunchBox] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LunchBox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LunchBox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LunchBox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LunchBox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LunchBox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LunchBox] SET ARITHABORT OFF 
GO

ALTER DATABASE [LunchBox] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LunchBox] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LunchBox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LunchBox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LunchBox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LunchBox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LunchBox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LunchBox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LunchBox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LunchBox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LunchBox] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LunchBox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LunchBox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LunchBox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LunchBox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LunchBox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LunchBox] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LunchBox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LunchBox] SET  READ_WRITE 
GO

ALTER DATABASE [LunchBox] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LunchBox] SET  MULTI_USER 
GO

ALTER DATABASE [LunchBox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LunchBox] SET DB_CHAINING OFF 
GO

