USE [LunchBox]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__ADMIN__USER_ID__0BC6C43E]') AND parent_object_id = OBJECT_ID(N'[dbo].[ADMIN]'))
ALTER TABLE [dbo].[ADMIN] DROP CONSTRAINT [FK__ADMIN__USER_ID__0BC6C43E]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__AGENCY__USER_ID__108B795B]') AND parent_object_id = OBJECT_ID(N'[dbo].[AGENCY]'))
ALTER TABLE [dbo].[AGENCY] DROP CONSTRAINT [FK__AGENCY__USER_ID__108B795B]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__HEALTHAGE__CREAT__22AA2996]') AND parent_object_id = OBJECT_ID(N'[dbo].[HEALTHAGENCY]'))
ALTER TABLE [dbo].[HEALTHAGENCY] DROP CONSTRAINT [FK__HEALTHAGE__CREAT__22AA2996]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PATENT__CREATED___32E0915F]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATENT]'))
ALTER TABLE [dbo].[PATENT] DROP CONSTRAINT [FK__PATENT__CREATED___32E0915F]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PATENT__HEALTHAG__31EC6D26]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATENT]'))
ALTER TABLE [dbo].[PATENT] DROP CONSTRAINT [FK__PATENT__HEALTHAG__31EC6D26]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PATENT__LAST_UPD__33D4B598]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATENT]'))
ALTER TABLE [dbo].[PATENT] DROP CONSTRAINT [FK__PATENT__LAST_UPD__33D4B598]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PATENT__PHYSICIA__30F848ED]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATENT]'))
ALTER TABLE [dbo].[PATENT] DROP CONSTRAINT [FK__PATENT__PHYSICIA__30F848ED]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PATENT__THEREAPI__300424B4]') AND parent_object_id = OBJECT_ID(N'[dbo].[PATENT]'))
ALTER TABLE [dbo].[PATENT] DROP CONSTRAINT [FK__PATENT__THEREAPI__300424B4]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PHYSICIAN__AGENT__1CF15040]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHYSICIAN]'))
ALTER TABLE [dbo].[PHYSICIAN] DROP CONSTRAINT [FK__PHYSICIAN__AGENT__1CF15040]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PHYSICIAN__CREAT__1DE57479]') AND parent_object_id = OBJECT_ID(N'[dbo].[PHYSICIAN]'))
ALTER TABLE [dbo].[PHYSICIAN] DROP CONSTRAINT [FK__PHYSICIAN__CREAT__1DE57479]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__THEREAPIS__AGENC__15502E78]') AND parent_object_id = OBJECT_ID(N'[dbo].[THEREAPIST]'))
ALTER TABLE [dbo].[THEREAPIST] DROP CONSTRAINT [FK__THEREAPIS__AGENC__15502E78]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__THEREAPIS__USER___164452B1]') AND parent_object_id = OBJECT_ID(N'[dbo].[THEREAPIST]'))
ALTER TABLE [dbo].[THEREAPIST] DROP CONSTRAINT [FK__THEREAPIS__USER___164452B1]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__USERS__ROLE_ID__07020F21]') AND parent_object_id = OBJECT_ID(N'[dbo].[USERS]'))
ALTER TABLE [dbo].[USERS] DROP CONSTRAINT [FK__USERS__ROLE_ID__07020F21]
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[ADMIN]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ADMIN]') AND type in (N'U'))
DROP TABLE [dbo].[ADMIN]
GO

/****** Object:  Table [dbo].[AGENCY]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENCY]') AND type in (N'U'))
DROP TABLE [dbo].[AGENCY]
GO

/****** Object:  Table [dbo].[HEALTHAGENCY]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HEALTHAGENCY]') AND type in (N'U'))
DROP TABLE [dbo].[HEALTHAGENCY]
GO

/****** Object:  Table [dbo].[PATENT]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PATENT]') AND type in (N'U'))
DROP TABLE [dbo].[PATENT]
GO

/****** Object:  Table [dbo].[PHYSICIAN]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHYSICIAN]') AND type in (N'U'))
DROP TABLE [dbo].[PHYSICIAN]
GO

/****** Object:  Table [dbo].[ROLES]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ROLES]') AND type in (N'U'))
DROP TABLE [dbo].[ROLES]
GO

/****** Object:  Table [dbo].[THEREAPIST]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[THEREAPIST]') AND type in (N'U'))
DROP TABLE [dbo].[THEREAPIST]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 11/11/2014 13:11:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USERS]') AND type in (N'U'))
DROP TABLE [dbo].[USERS]
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[ADMIN]    Script Date: 11/11/2014 13:11:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ADMIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[NAME] [varchar](30) NULL,
	[CREATEDON] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[AGENCY]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AGENCY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ADDRESS] [varchar](50) NULL,
	[USER_ID] [int] NULL,
	[TAX_ID] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[HEALTHAGENCY]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HEALTHAGENCY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](40) NULL,
	[ADDRESS] [varchar](60) NULL,
	[PHONE] [varchar](12) NULL,
	[TAX_ID] [varchar](20) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[PATENT]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PATENT](
	[PATID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NULL,
	[PRIMARY_PHONE] [varchar](11) NULL,
	[SECONDARY_PHONE] [varchar](11) NULL,
	[DOB] [date] NULL,
	[SSN] [varchar](15) NULL,
	[MEDICARE] [varchar](10) NULL,
	[MEDICALID] [varchar](10) NULL,
	[INSURANCE] [varchar](10) NULL,
	[THEREAPIST_ID] [int] NULL,
	[PHYSICIAN] [int] NULL,
	[HEALTHAGENCY] [int] NULL,
	[MEDICAL_NECESSITY] [varchar](60) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [date] NULL,
	[LAST_UPDATED_BY] [int] NULL,
	[LAST_UPDATED_DATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[PATID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[PHYSICIAN]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PHYSICIAN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FULL_NAME] [varchar](50) NULL,
	[EMAIL] [varchar](40) NULL,
	[PHONE] [varchar](12) NULL,
	[AGENT_ID] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[ROLES]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ROLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE] [varchar](20) NULL,
	[DESCRIPTION] [varchar](30) NULL,
	[CREATEDON] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[THEREAPIST]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[THEREAPIST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AGENCY_ID] [int] NULL,
	[USER_ID] [int] NULL,
	[TYPE_CODE] [varchar](5) NULL,
	[FIRST_NAME] [varchar](20) NULL,
	[LAST_NAME] [varchar](20) NULL,
	[INTERNAL_EMAIL] [varchar](25) NULL,
	[PHONE_NUMBER] [varchar](12) NULL,
	[ZIP_CODE_BASE] [varchar](6) NULL,
	[TAX_ID] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [LunchBox]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 11/11/2014 13:11:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](20) NULL,
	[PASS_WORD] [varchar](20) NULL,
	[ROLE_ID] [int] NULL,
	[CREATEDON] [date] NULL,
	[LASTLOGIN] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ADMIN]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[AGENCY]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[HEALTHAGENCY]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[PATENT]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[PATENT]  WITH CHECK ADD FOREIGN KEY([HEALTHAGENCY])
REFERENCES [dbo].[HEALTHAGENCY] ([ID])
GO

ALTER TABLE [dbo].[PATENT]  WITH CHECK ADD FOREIGN KEY([LAST_UPDATED_BY])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[PATENT]  WITH CHECK ADD FOREIGN KEY([PHYSICIAN])
REFERENCES [dbo].[PHYSICIAN] ([ID])
GO

ALTER TABLE [dbo].[PATENT]  WITH CHECK ADD FOREIGN KEY([THEREAPIST_ID])
REFERENCES [dbo].[THEREAPIST] ([ID])
GO

ALTER TABLE [dbo].[PHYSICIAN]  WITH CHECK ADD FOREIGN KEY([AGENT_ID])
REFERENCES [dbo].[AGENCY] ([ID])
GO

ALTER TABLE [dbo].[PHYSICIAN]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[THEREAPIST]  WITH CHECK ADD FOREIGN KEY([AGENCY_ID])
REFERENCES [dbo].[AGENCY] ([ID])
GO

ALTER TABLE [dbo].[THEREAPIST]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[USERS]  WITH CHECK ADD FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[ROLES] ([ID])
GO

